"""Renders a Quotation/Invoice ORM record into a PDF (reportlab).

Currency/tax are hardcoded to INR/18% GST per the Phase 4 PLAN.md decision —
not configurable, matches the rest of the pipeline (see app.agents.tools.TAX_RATE).
"""

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet

from app.models.orm import Customer, Invoice, Quotation

_styles = getSampleStyleSheet()


def _format_money(value: float, currency: str) -> str:
    symbol = "₹" if currency == "INR" else currency + " "
    return f"{symbol}{value:,.2f}"


def render_document_pdf(document: Quotation | Invoice, customer: Customer | None) -> bytes:
    kind = "INVOICE" if isinstance(document, Invoice) else "QUOTATION"
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)

    elements: list[Any] = [
        Paragraph("EnterpriseFlow", _styles["Title"]),
        Paragraph(kind, _styles["Heading2"]),
        Spacer(1, 8),
        Paragraph(f"Reference: {document.id}", _styles["Normal"]),
        Paragraph(f"Date: {document.created_at.strftime('%d %b %Y')}", _styles["Normal"]),
        Paragraph(f"Status: {document.status.replace('_', ' ').title()}", _styles["Normal"]),
    ]

    if customer:
        elements.append(Spacer(1, 8))
        elements.append(Paragraph("Billed to:", _styles["Heading4"]))
        elements.append(Paragraph(customer.name or "Customer", _styles["Normal"]))
        elements.append(Paragraph(customer.phone_number, _styles["Normal"]))
        if customer.email:
            elements.append(Paragraph(customer.email, _styles["Normal"]))

    elements.append(Spacer(1, 14))

    table_data = [["Item", "Qty", "Unit Price", "Line Total"]]
    for item in document.items:
        table_data.append(
            [
                str(item.get("product_name", item.get("name", "Item"))),
                str(item.get("quantity", 1)),
                _format_money(float(item.get("unit_price", 0)), document.currency),
                _format_money(float(item.get("line_total", 0)), document.currency),
            ]
        )

    table = Table(table_data, colWidths=[80 * mm, 20 * mm, 35 * mm, 35 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 10))

    totals_data = [
        ["Subtotal", _format_money(float(document.subtotal), document.currency)],
        ["GST (18%)", _format_money(float(document.tax_amount), document.currency)],
        ["Total", _format_money(float(document.total), document.currency)],
    ]
    totals_table = Table(totals_data, colWidths=[150 * mm, 40 * mm])
    totals_table.setStyle(
        TableStyle(
            [
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
                ("LINEABOVE", (0, 2), (-1, 2), 0.75, colors.HexColor("#1f2937")),
            ]
        )
    )
    elements.append(totals_table)

    if document.customer_message:
        elements.append(Spacer(1, 16))
        elements.append(Paragraph("Note:", _styles["Heading4"]))
        elements.append(Paragraph(document.customer_message, _styles["Normal"]))

    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            f"Generated by EnterpriseFlow on {datetime.now().strftime('%d %b %Y, %H:%M')}",
            _styles["Normal"],
        )
    )

    doc.build(elements)
    return buffer.getvalue()
